### ISSUE TITLE
Font size? 

### ISSUE THREAD

**Issue by p1r473** [mrusme/lemon#1]
Any way to set the font size via the JSON?
I see it defaults to 12 in the code.

**Comment by mrusme** [comment]
Not yet but it should be rather easy to add it to the code. Check ledhat.py and resource_api.py. :-) Feel free to PR it.

Fyi: 12px was the size I found best for reading. Consider that we have only a few "pixels" available. A smaller font will probably make things slightly harder to read, especially while in motion.
